"""
This type stub file was generated by pyright.
"""

from .config import default_config, get_config, set_config
from .decorators import log_function, log_method
from .logger import Logger

"""This is the __init__.py file.txt for the LogFusion files."""
__all__ = ["Logger", "default_config", "get_config", "log_function", "log_method", "set_config"]
