"""
This type stub file was generated by pyright.
"""

from typing import Any, ParamSpec

"""
This type stub file was generated by pyright.
"""
P = ParamSpec("P")
def log_function(config: dict[str, Any] | None = ...) -> Any:
    """Decorator to log function calls.

    Args:
        config (dict, optional): The logging configuration. If not provided, the default configuration will be used.
    """
    ...

def log_method(config: dict[str, Any] | None = ...):
    """Decorator to log method calls.

    Args:
        config (dict, optional): The logging configuration. If not provided, the default configuration will be used.
    """
    ...

