from abc import ABC, abstractmethod

"""Abstract base class for logging handlers."""

class BaseHandler(ABC):
    @abstractmethod
    def debug(self, message: str) -> None: ...
    @abstractmethod
    def info(self, message: str) -> None: ...
    @abstractmethod
    def warning(self, message: str) -> None: ...
    @abstractmethod
    def error(self, message: str) -> None: ...
    @abstractmethod
    def critical(self, message: str) -> None: ...
    @abstractmethod
    def exception(self, message: str, exc_info: Exception) -> None: ...
