"""
This type stub file was generated by pyright.
"""

from typing import Any

"""Load the configuration from pyproject.toml."""
default_config: dict[str, Any] = ...

def set_config(config: dict[str, Any]) -> None:
    """Set the logging configuration.

    Args:
        config (Dict[str, Any]): The logging configuration.
    """
    ...

def get_config() -> dict[str, Any]:
    """Get the logging configuration.

    Returns:
        Dict[str, Any]: The logging configuration.
    """
    ...
